DROP ALL OBJECTS;

CREATE TABLE IF NOT EXISTS USERS (
    id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULl,
    email VARCHAR(512) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS ITEMS (
    id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR NOT NULL,
    is_available BOOLEAN NOT NULL,
    owner_id BIGINT NOT NULL REFERENCES USERS (ID),
    request_id BIGINT NOT NULL,
    CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS BOOKINGS (
    id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    start_time DATETIME NOT NULL,
    end_time DATETIME NOT NULL,
    status varchar(10) NOT NULL,
    item_id BIGINT NOT NULL REFERENCES ITEMS (ID),
    booker_id BIGINT NOT NULL REFERENCES USERS (ID),
    CONSTRAINT pk_booking PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS REQUESTS (
    id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    description varchar NOT NULL,
    requestor_id BIGINT NOT NULL REFERENCES USERS (ID),
    creation_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    text VARCHAR NOT NULL,
    item_id BIGINT NOT NULL REFERENCES ITEMS (id),
    author_id BIGINT NOT NULL REFERENCES USERS (id),
    creation_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);